### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by lukescott** [gajus/flow-runtime#124]
This is a:

 - [X] Feature Request

Which concerns:

 - [ ] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

TypeScript support is being added to babel. See https://github.com/babel/babylon/issues/320. Parser support was merged here https://github.com/babel/babylon/pull/523.

This could be done with a different plugin, but (I would assume) the goals are similar. Hence the feature request.

**Comment by fabiandev** [comment]
I've recently published a take on generating runtime type checks by utilizing the TypeScript transformation API, which was just released with TS 2.4: https://github.com/fabiandev/ts-runtime

I'm also looking forward to check out babel support for TypeScript. In the meanwhile you may give [ts-runtime](https://github.com/fabiandev/ts-runtime) a try. It's still under development, but I'd appreciate any feedback and/or bug reports.

**Comment by fabiandev** [comment]
@lukescott if you're interested, I've created a playground to test [ts-runtime](https://github.com/fabiandev/ts-runtime) in a browser: https://fabiandev.github.io/ts-runtime/

**Comment by gajus** [comment]
No action here.
