### ISSUE TITLE
migrate to react-codemirror2

### ISSUE THREAD

**Issue by scniro** [gajus/flow-runtime#143]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2435%20Funded-%2300A156.svg" />](https://issuehunt.io/r/gajus/flow-runtime/issues/143)

react-codemirror has major [outstanding issues](https://github.com/JedWatson/react-codemirror/issues) and many users including myself suspect this package has been abandoned. I authored [react-codemirror2](https://github.com/scniro/react-codemirror2) and plan to actively maintain this as a successor moving forward. I encourage you try the new package in your project. Likewise, feel free to open up any issue should you encounter trouble and I'll be on it. Same with general suggestions/improvements - I'm aiming to build it up collaboratively so if you had any shortcomings with the original package please let me know.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $35.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($35.00)

### Submitted pull Requests
- [#251 refactor: migrate to react-codemirror2](https://issuehunt.io/r/gajus/flow-runtime/pull/251)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/gajus/flow-runtime/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by mhatvan** [comment]
Hey @scniro, is the migration to react-codemirror2 still relevant to you? I could take a look at providing a PR.

**Comment by gajus** [comment]
Yeah, go ahead.

**Comment by gajus** [comment]
Got for it.

**Comment by mhatvan** [comment]
@gajus I just saw that the issuehunt reward is still outstanding for this issue. Are you aware of that?

**Comment by gajus** [comment]
I was not. Sorry for the inconvenience.
