### ISSUE TITLE
Deep Object and Array Types break at runtime

### ISSUE THREAD

**Issue by KillianHmyd** [gajus/flow-runtime#197]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?
The following code breaks at runtime:

```
type ItemType = {
  designation: string,
  price?: number,
  weight?: number
}

type ParcelType<CustomItemType> = {
  nbItems: number,
  item: CustomItemType
}

type ParcelsDeliveryType<CustomParcelType> = {
  parcels: CustomParcelType[],
  country: string
}

const shirt: ItemType = {
  designation: 'shirt',
  price: 20,
  weight: 0.5
}

const freeGoodie: ItemType = {
  designation: 'goodie',
  weight: 0.01
}

const parcelsDelivery: ParcelsDeliveryType<ParcelType<ItemType>> = {
  country: 'FRANCE',
  parcels: [
    {
    	nbItems: 2,
    	item: shirt
    },
    {
      nbItems: 1,
      item: freeGoodie
    }
  ]
}
```

The error : 
```
parcels[1].item.price must be a number

Expected: number

Actual Value: undefined

Actual Type: void
```

---

### What is the expected behaviour?

The code shouldn't break at runtime. There is no Flow apparent error.

---

### Which package versions are you using?
0.17.0

**Comment by jedwards1211** [comment]
I'm looking into this
@phpnode looks like the problem stems from using using the `recorded` property in `TypeParameter`:
![image](https://user-images.githubusercontent.com/1448194/50049337-f9628580-00a8-11e9-9110-9441eb0aa341.png)
I think it's recording the type of the first `item` in the array, which has `price: number`, and doesn't match the second item in the array.
