### ISSUE TITLE
Migrate site to Webpack 2, 3 or 4

### ISSUE THREAD

**Issue by goodmind** [gajus/flow-runtime#235]
This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [x] Other

Which concerns:

 - [ ] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [x] The documentation website

---

Also would be nice to migrate to babel 7, because I can't even update site currently to use latest packages

**Comment by vlsergey** [comment]
Fixed by #250
