### ISSUE TITLE
Could not resolve libs in .flowconfig?

### ISSUE THREAD

**Issue by JounQin** [gajus/flow-runtime#53]
This is a:

 - Question

Which concerns:

 - babel-plugin-flow-runtime
---

### What is the current behaviour?
```
flow-runtime: Cannot resolve type: Card
```

---

### What is the expected behaviour?
resolve declare types correctly

---

### Which package versions are you using?
0.4.0

---

My *.flowconfig*
```
[ignore]
.*/node_modules/.*
.*/test/.*
.*/build/.*
.*/dist/.*
.*/coverage/.*

[include]
.*/src/.*

[libs]
src/flow

[options]
unsafe.enable_getters_and_setters=true
```

My *src/flow/card.js*
``` js
declare type Card = {
  cardTypeId: string,
  cardTypeName: void | string,
  cardId: string,
  cardTimes: number,
  cardLimit: string,
  cardDiscount: number,
  isValueCard: boolean,
  cardExpired: string,
  cardStyle: number
}
```

**Comment by phpnode** [comment]
we don't support `[include]` from `.flowconfig` yet, if you explicitly `import` or `require` the file containing the declaration it should work throughout the rest of your app, but it would be nice to handle this properly.

**Comment by JounQin** [comment]
Should it be supported to use `Card` type in `whatever.js` without import it?

My point is the `libs` prop in `.flowconfig`, and I can't use `Card` type automatically.

For now, I must do this:
``` js
// flow/Card.js
export type Card = {}
```

``` app.js
// src/app.js

import {Card} from 'flow/Card' // I hope that I don't need to do this with `libs` in `.flowconfig`

export default test = (card: Card) => true
```

**Comment by phpnode** [comment]
If you've done `declare class` then yes you should be able to use it without referencing it but it's not fully supported yet. The best approach at the moment is to use `flow-runtime-cli` to generate a single (often quite large) file which includes all your definitions, and then include that once at the entry point of your app, then everything should work:

```sh
yarn add --dev flow-runtime-cli
flow-runtime-cli generate src > typedefs.js
```

then in your entry point:

```js
if (process.env.NODE_ENV === 'development') { // presuming you don't want it in prod
  require('./typedefs');
}
```

and now it *should* work, but `flow-runtime-cli` is very new so if you run into issues please report them

**Comment by phpnode** [comment]
to test a theory, please wrap your declaration in a declare module, like this -
```js
declare module "testing-something" {
  declare type Card = {
    cardTypeId: string,
    cardTypeName: void | string,
    cardId: string,
    cardTimes: number,
    cardLimit: string,
    cardDiscount: number,
    isValueCard: boolean,
    cardExpired: string,
    cardStyle: number
  }

  declare type MbrCard = Card & {}
}
```

and in `src/test/card.js`

`import type {Card} from 'testing-something';`

Now when you run `flow-runtime generate ./src > ./src/typedefs.js` do you get some output, or is it still blank?

Will try and get a fix for this in a week or so but I'm busy with work at the moment.

**Comment by JounQin** [comment]
Sorry but it is still blank, I will just import the type by myself for now, thx a lot.

**Comment by phpnode** [comment]
@JounQin one last thing to try, undo the wrapping from my last comment and put the `Card` definition in a file in your `flow-typed` directory and run generate again, does that make a difference?

**Comment by max-mykhailenko** [comment]
`babel-plugin-flow-runtime` don't use types from `flow-typed` directory.

**Comment by bradennapier** [comment]
Also running into this issue.

**Comment by stepankuzmin** [comment]
Same problem here with external flow-typed libraries

```
[ignore]
.*/node_modules/documentation/.*
.*/node_modules/findup/.*
.*/node_modules/jsonlint-lines-primitives/.*
.*/node_modules/jss/.*
.*/node_modules/unflowify/.*

[include]

[libs]
node_modules/mapbox-gl/flow-typed

[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

[lints]
```

**Comment by JounQin** [comment]
I'm not using flow any more, so close this for now.

Please report another issue if you like.

**Comment by max-mykhailenko** [comment]
@JounQin what you are using instead of?

**Comment by gajus** [comment]
For what is worth, there is a major update of flow-runtime coming in couple of weeks.

Sounds like @JounQin switched to TS.

**Comment by gajus** [comment]
I will go through all the open issues after the upgrade is released.

**Comment by JounQin** [comment]
`flow-runtime` is great, but `flow` itself sucks.

Good luck.
