### ISSUE TITLE
Instance variables undefined

### ISSUE THREAD

**Issue by basilfx** [gajus/flow-runtime#92]
This is a:

 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [X] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

```es6
export default class Thumbnail extends React.Component<DefaultProps, Props, void> {
    foo: boolean;

    constructor(props: Props) {
        super(props);

        this.foo = true; // -> set to true!

        console.log(this.foo); // -> true here.
    }

    render() {
        console.log(this.foo); // -> undefined here, expected true.

        return <span>Something</span>;
    }
}
```

After some debugging, I found the following 'difference'. This code is executed directly after the constructor.

![schermafbeelding_2017-04-11_om_19_52_32](https://cloud.githubusercontent.com/assets/815976/24923105/d00cdb18-1ef0-11e7-8e1e-d2cdb2cb4713.png)

---

### What is the expected behaviour?

The expected behaviour is observed when I remove `flow-runtime` from my `.babelrc`. I expect to see `true` in the console once the `render()` method is invoked.

This is my `.babelrc`:

```json
{
    "presets": [
        ["env", {
            "targets": {
                "chrome": 57
            },
            "modules": false,
        }],
        "react",
        "stage-0"
    ],
    "plugins": [
        "transform-runtime",
        "transform-decorators-legacy",
        "transform-react-display-name",
        "react-hot-loader/babel",
        ["flow-runtime", {
            "assert": true,
            "annotate": true
        }]
    ]
}
```

---

### Which package versions are you using?

* `flow-runtime@0.10.0`
* `babel-plugin-flow-runtime@0.10.0`

**Comment by basilfx** [comment]
I can also confirm that `flow-runtime` works when I change my `.babelrc` to use the `babel-preset-es2015` preset instead of `babel-preset-env` (with Chrome 57 as target since I want to use native goodies).

**Comment by phpnode** [comment]
Ok, I can't replicate the error using the online demo page, from your second comment it sounds like it only happens when native classes are used, but when I try and recreate without transpilation then everything still works, so I'm not quite sure what's going on here. I guess this could be related to the enumerability of the class property, so if you just remove the class property declaration for `foo` does it go away? What happens if you give `foo` a default value, `foo: boolean = false`, does that affect the result?

**Comment by basilfx** [comment]
Some more tests (same `.babelrc`):

```es6
// @flow

import React from 'react';

/**
 * Media file thumbnail component.
 */
export default class Minimal extends React.Component {
    foo: boolean = false; // -> Note: false

    /**
     * @inheritdoc
     */
    constructor(props: Object) {
        super(props);

        this.foo = true; // -> Note: true
    }

    render() {
        console.log(this.foo); // -> outputs false instead of true

        return <span>Something</span>;
    }
}
```

and also (note the `$FlowFixMe`):

```
// @flow

import React from 'react';

/**
 * Media file thumbnail component.
 */
export default class Minimal extends React.Component {
    /**
     * @inheritdoc
     */
    constructor(props: Object) {
        super(props);

        // $FlowFixMe
        this.foo = true;
    }

    render() {
        // $FlowFixMe
        console.log(this.foo); // -> outputs true

        return <span>Something</span>;
    }
}
```

**Comment by phpnode** [comment]
hmm, I wonder if this is related to plugin ordering in your `.babelrc` as I still cannot replicate here. Please try enabling babel's `passPerPreset` option, and move flow-runtime up to the top of your list of plugins.
